name: hap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=4=2_sapphirerapids
  - asttokens=2.4.1=pyhd8ed1ab_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cairomm-1.16=1.16.2=h7e731d7_1
  - certifi=2024.8.30=py310h06a4308_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.5=py310hf71b8c6_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.1=h55d465d_3
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - graph-tool=2.71=py310hd4e9e38_400
  - graph-tool-base=2.71=py310hfe7118a_400
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk3=3.24.34=h13ada96_0
  - harfbuzz=4.3.0=hf52aaf7_2
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=73.2=h59595ed_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libboost=1.84.0=h8013b2b_2
  - libboost-python=1.84.0=py310ha2bacc8_6
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.7.68=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgirepository=1.78.1=h003a4f0_1
  - libglib=2.80.2=hf974151_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - librsvg=2.54.4=h7abd40a_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib=3.9.2=py310h06a4308_0
  - matplotlib-base=3.9.2=py310hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pango=1.50.7=hbd2fdc8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py310ha75aee5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycairo=1.25.0=py310hda9f760_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pygobject=3.46.0=py310h30b043a_1
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.0=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - setuptools=75.1.0=py310h06a4308_0
  - sigcpp-3.0=3.6.0=h59595ed_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sparsehash=2.0.4=hcb278e6_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - torchaudio=2.4.0=py310_cu121
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu121
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - urllib3=2.2.2=py310h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - annotated-types==0.7.0
      - cachetools==5.5.0
      - click==8.1.7
      - coloredlogs==15.0.1
      - cyvcf2==0.31.1
      - fsspec==2024.9.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.20.0
      - google-api-python-client==2.147.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - grpcio-status==1.66.1
      - httplib2==0.22.0
      - humanfriendly==10.0
      - joblib==1.4.2
      - nvidia-nccl-cu12==2.23.4
      - opt-einsum==3.3.0
      - pandas==2.2.3
      - patsy==0.5.6
      - pgmpy==0.1.26
      - proto-plus==1.24.0
      - protobuf==5.28.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.4
      - pysam==0.22.1
      - pytz==2024.2
      - qrcode==8.0
      - rsa==4.9
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - statsmodels==0.14.3
      - threadpoolctl==3.5.0
      - tqdm==4.66.5
      - tzdata==2024.2
      - uritemplate==4.1.1
      - vcfpy==0.13.8
      - xgboost==2.1.1
prefix: /home/mok23003/miniconda3/envs/hap
